export const APP_VERSION = '1.6.0'

export type TipoCambio = 'mayor' | 'media' | 'menor'

export interface EntradaChangelog {
  version: string
  fecha: string
  tipo: TipoCambio
  cambios: string[]
}

export const CHANGELOG: EntradaChangelog[] = [
  {
    version: '1.6.0',
    fecha: '02/06/2026',
    tipo: 'mayor',
    cambios: [
      'Fase A migración Supabase: botón "⬆️ Subir mis datos a Supabase" en Ajustes (solo Rubén)',
      'Subida completa: asegurarUsuarioRuben() + DELETE previo + INSERT sesiones + INSERT registros_peso',
      'Barra de progreso con porcentaje durante la subida',
      'Botón "✅ Verificar datos en Supabase": muestra el COUNT real de entrenos y registros_peso de Rubén',
      'Sin cambios en login, useSupabaseSync ni flujo de datos locales — subida 100% manual',
    ],
  },
  {
    version: '1.5.4',
    fecha: '30/04/2026',
    tipo: 'mayor',
    cambios: [
      'RESCATE: función rescatarDatosRuben() en App.tsx — antes de cualquier hidratación del store, copia fitlog-store → fitlog-store-ruben si este último tiene 0 sesiones',
      'GUARDIA DOBLE en actualizarHistorialRemoto: isRubenActivo() + lectura directa de fitlog_usuario_activo — defensa en profundidad',
      'entrarComoRuben() confirmado sin ninguna llamada que modifique historialSesiones o registrosPeso',
    ],
  },
  {
    version: '1.5.3',
    fecha: '30/04/2026',
    tipo: 'mayor',
    cambios: [
      'BUG 1.5.2: guards usaban getStoreKey() === "fitlog-store-ruben" — falso positivo cuando no había sesión activa, bloqueaba actualizarHistorialRemoto para invitados',
      'Nueva función isRubenActivo(): devuelve true SOLO cuando esRuben===true está confirmado — nunca como fallback sin sesión',
      'Los tres guards (importarHistorial, importarHistorialCompleto, actualizarHistorialRemoto) usan isRubenActivo() — invitados nunca bloqueados',
      'Protección de datos de Rubén mantenida íntegra',
    ],
  },
  {
    version: '1.5.2',
    fecha: '30/04/2026',
    tipo: 'mayor',
    cambios: [
      'PROTECCIÓN RUBÉN: importarHistorial/importarHistorialCompleto/actualizarHistorialRemoto bloqueadas con console.error cuando el usuario activo es Rubén',
      'PROTECCIÓN RUBÉN: refreshFromSupabase() tiene guardia absoluta — retorna inmediatamente si usuario.esRuben',
      'PROTECCIÓN RUBÉN: entrarComoRuben() ya NO carga datos de Supabase bajo ninguna circunstancia — localStorage es la única fuente de verdad',
      'PROTECCIÓN RUBÉN: botón "Recargar desde Supabase" en Ajustes bloqueado para Rubén con mensaje explicativo',
      'Debug: botón "Ver datos en localStorage" muestra el tamaño de fitlog-store-ruben en verde/rojo antes de hacer click',
    ],
  },
  {
    version: '1.5.1',
    fecha: '30/04/2026',
    tipo: 'mayor',
    cambios: [
      'BUG CRÍTICO: eliminada guardia "sesionActiva !== null" en pullHistorialInvitado — cancelaba el pull exactamente cuando la tarjeta Último entreno estaba visible',
      'El pull ahora funciona durante sesiones activas — actualizarHistorialRemoto es seguro (nunca toca sesionActiva)',
      'La tarjeta Último entreno se actualiza en tiempo real para invitados',
    ],
  },
  {
    version: '1.5.0',
    fecha: '30/04/2026',
    tipo: 'mayor',
    cambios: [
      'BUG: quitada guardia navigator.onLine — Safari iOS devuelve false aunque haya WiFi',
      'BUG: condición > localCount → > 0 — antes no actualizaba si los counts coincidían aunque el contenido fuera distinto',
      'Ahora el pull siempre actualiza cuando Supabase devuelve sesiones (> 0)',
      'usePullStatus(): hook que devuelve ok/err/idle tras cada pull',
      'Indicador visual ✓ verde / ✗ rojo junto al countdown — confirma si el pull llega a Supabase o falla',
    ],
  },
  {
    version: '1.4.9',
    fecha: '30/04/2026',
    tipo: 'mayor',
    cambios: [
      'Timer iOS: reemplazado setInterval por requestAnimationFrame — iOS no puede matar rAF mientras la app está visible',
      'rAF loop compara Date.now() con lastPull — dispara pull cuando han pasado 5 segundos',
      'Nuevo evento: window.online — pull inmediato al recuperar conexión tras estar offline',
      'visibilitychange sigue activo — pull al desbloquear el iPhone o volver desde otra app',
      'useSyncCountdown(): hook que devuelve el countdown 5→0, actualiza solo una vez por segundo (no a 60fps)',
      'Layout: indicador ↻Xs en la esquina superior derecha, solo visible para invitados',
      'cancelAnimationFrame limpio en el cleanup del hook',
    ],
  },
  {
    version: '1.4.7',
    fecha: '30/04/2026',
    tipo: 'mayor',
    cambios: [
      'Intervalo de pull reducido a 5 segundos (antes 10s) para ver cambios más rápido',
      'console.log en pullHistorialInvitado: muestra remoto/local antes y después del merge',
      'console.log en actualizarHistorialRemoto: muestra counts antes/después del merge',
      'setUltimaSync(Date.now()) tras cada pull exitoso — fuerza re-render aunque el historial no cambie',
      'Tarjeta Último entreno: muestra hora del último sync (↻HH:MM:SS) para confirmar que se actualiza',
      'ultimaSyncTimestamp en el store: campo persistente que cambia en cada poll exitoso',
    ],
  },
  {
    version: '1.4.6',
    fecha: '30/04/2026',
    tipo: 'mayor',
    cambios: [
      'Refresco automático para invitados: pull de Supabase cada 10 segundos y al recuperar foco',
      'visibilitychange: al volver a la app desde otra pestaña o desbloquear el móvil se recarga el historial',
      'Nuevo store action actualizarHistorialRemoto: solo toca historialSesiones, nunca sesionActiva ni pesos',
      'Fusión segura: sesiones locales pendientes (no sincronizadas) sobreviven al pull remoto',
      'Guard de sesión activa: el pull se cancela si hay un entrenamiento en curso',
      'Al completar sesión como invitado: push a Supabase + pull inmediato para confirmar',
      'Para Rubén: sin cambios, sus datos siguen en localStorage + Google Sheets',
    ],
  },
  {
    version: '1.4.5',
    fecha: '30/04/2026',
    tipo: 'mayor',
    cambios: [
      'BUG CRÍTICO: eliminado window.location.reload() en LoginPage que causaba 404 a los 3 segundos',
      'Eliminado código de desregistro de service workers (sessionStorage sw-cleared) — ya no hace falta con sw.js estándar',
      'FK constraint Supabase: asegurarUsuarioRuben() crea la fila en tabla usuarios antes de cualquier sync',
      'asegurarUsuarioRuben() es idempotente — upsert con ignoreDuplicates, seguro llamarlo varias veces',
      'entrarComoRuben(): asegurarUsuarioRuben() se llama siempre al hacer login, con o sin datos locales',
      'Los datos locales de Rubén siguen protegidos: no se sobreescriben si localStorage tiene sesiones o pesos',
    ],
  },
  {
    version: '1.4.4',
    fecha: '30/04/2026',
    tipo: 'mayor',
    cambios: [
      'ESTABILIZACIÓN: eliminado todo el auto-sync (realtime, visibilitychange, refresh al montar)',
      'Política de sync: solo PUSH al guardar y PULL manual al hacer login o desde Ajustes',
      'Rubén: entrarComoRuben() ya NO sobreescribe datos locales si hay sesiones en localStorage',
      'Solo carga de Supabase si localStorage está completamente vacío',
      'Service worker restaurado a sw.js (sin sufijo de versión) para que el iPhone actualice correctamente',
      'Debug localStorage visible en LoginPage: sesiones, pesos, UUID y fuente de datos sin necesitar DevTools',
      'Eliminados refreshFromSupabase() automáticos en HomePage y TendenciasPage al montar',
    ],
  },
  {
    version: '1.4.3',
    fecha: '29/04/2026',
    tipo: 'mayor',
    cambios: [
      'BUG CRÍTICO: eliminado polling cada 5s que sobreescribía datos locales no sincronizados',
      'Merge inteligente: el refresh de Supabase nunca destruye sesiones con sincronizado=false',
      'refreshFromSupabase usa importarHistorial (merge) en lugar de importarHistorialCompleto (replace)',
      'console.log en handleGuardar para verificar que el store se actualiza correctamente',
      'Diagnóstico de datos en Ajustes: total sesiones, pendientes, última sesión con ejercicios y estado de sync',
      'useSupabaseSync simplificado: solo realtime + visibilitychange (sin polling agresivo)',
    ],
  },
  {
    version: '1.4.2',
    fecha: '29/04/2026',
    tipo: 'mayor',
    cambios: [
      'Sync reactivo 4-en-1: polling cada 5s + visibilitychange + refresh al entrar en pantalla + Supabase Realtime',
      'Polling cada 5s en background mientras la app está abierta (no bloquea la UI)',
      'Al volver al primer plano (tab focus) recarga inmediata desde Supabase',
      'HomePage, TendenciasPage y SesionPage recargan al montar (spinner discreto en cabecera)',
      'Supabase Realtime: suscripción postgres_changes en tabla entrenos — actualización instantánea al recibir cambios',
      'refreshFromSupabase es segura durante sesión activa: solo toca historialSesiones y registrosPeso, nunca sesionActiva',
    ],
  },
  {
    version: '1.4.1',
    fecha: '29/04/2026',
    tipo: 'mayor',
    cambios: [
      'Supabase como fuente de verdad: al hacer login siempre se cargan datos frescos de Supabase antes de entrar',
      'importarHistorialCompleto: reemplaza el caché local completamente (no hace merge)',
      'Spinner "Cargando datos..." durante la carga inicial en LoginPage',
      'Rubén también carga desde Supabase al entrar (usando su UUID persistente)',
      'Botón "Recargar datos desde Supabase" en Ajustes → Sincronización disponible en cualquier momento',
    ],
  },
  {
    version: '1.4.0',
    fecha: '29/04/2026',
    tipo: 'mayor',
    cambios: [
      'Cola de sincronización con reintentos: cada ejercicio se encola en localStorage y reintenta cada 30s o al volver la conexión',
      'Optimistic UI: la sesión se marca como sincronizada al instante al cerrar; si falla, revierte a pendiente',
      'Indicador de sync en la cabecera de la sesión: punto verde parpadeante / fijo / rojo',
      'Service worker versionado (sw-140.js) para forzar actualización en cada despliegue',
      'Desregistro agresivo de SWs obsoletos al cargar LoginPage (una sola vez vía sessionStorage)',
      'Versión visible en la cabecera de Ajustes sin necesidad de bajar',
    ],
  },
  {
    version: '1.3.9',
    fecha: '29/04/2026',
    tipo: 'media',
    cambios: [
      'Página /debug-supabase: diagnóstico completo en pantalla (sin necesitar DevTools)',
      'Test conexión: SELECT count(*) con respuesta cruda visible',
      'Test insert: INSERT de prueba con error completo (message, code, hint) visible en pantalla',
      'Ver pendientes: muestra todos los registros sincronizado=false del store',
      'Subir 1 pendiente: sube el primer pendiente y muestra la respuesta raw de Supabase',
    ],
  },
  {
    version: '1.3.8',
    fecha: '29/04/2026',
    tipo: 'mayor',
    cambios: [
      'BUG CRÍTICO: marcarSesionSincronizada/marcarPesoSincronizado ahora se llaman tras sync exitosa — los registros ya dejan de quedar como "pendientes"',
      'importarHistorial ahora hace MERGE: conserva registros locales pendientes en lugar de sobreescribirlos',
      'forzarSincronizacionPendientes(): sube todos los registros pendientes uno a uno y los marca',
      'Auto-sync al hacer login: los pendientes locales se suben antes de cargar datos remotos',
      'Botón "Forzar sincronización con Supabase" en Ajustes visible para todos los usuarios',
    ],
  },
  {
    version: '1.3.7',
    fecha: '29/04/2026',
    tipo: 'media',
    cambios: [
      'Sync por ejercicio: cada "Guardar y siguiente" envía datos a Supabase inmediatamente (no se pierde nada si la sesión no termina)',
      'sincronizarEntrenoSupabase ahora es idempotente: DELETE del sesion_id antes del INSERT para evitar duplicados',
      'console.error explícito en todas las funciones de sync de Supabase para diagnóstico en DevTools',
      '"Verificar Supabase" en Ajustes: muestra SELECT usuarios + INSERT/DELETE entrenos con resultados detallados',
      '@supabase/supabase-js actualizado a v2.105.1',
    ],
  },
  {
    version: '1.3.6',
    fecha: '28/04/2026',
    tipo: 'media',
    cambios: [
      'Rubén usa un UUID persistente (fitlog-ruben-uuid) en todas las llamadas a Supabase',
      'Error toast visible en rojo si falla la sync con Supabase (entrenos y peso)',
      'handleFinalizar es async: espera la sync antes de navegar, muestra "Sincronizando…"',
      'Botón "Verificar conexión Supabase" en Ajustes (solo Rubén): INSERT/DELETE de prueba',
    ],
  },
  {
    version: '1.3.5',
    fecha: '28/04/2026',
    tipo: 'media',
    cambios: [
      'Resumen de sesión: línea "🏆 ¡Nuevo récord! +Xkg respecto al último entreno" en verde cuando se supera el peso máximo histórico',
      'Resumen de sesión: línea "⭐ ¡Primera vez!" en dorado si es la primera vez que se realiza el ejercicio',
      'Texto WhatsApp: incluye "🏆 ¡Nuevo récord!" y "⭐ ¡Primera vez!" por ejercicio',
    ],
  },
  {
    version: '1.3.4',
    fecha: '28/04/2026',
    tipo: 'media',
    cambios: [
      'Colores de peso definitivos: Serie 1 vs máximo histórico, Series 2+ vs serie anterior; igual siempre sin color',
      'Si un campo está vacío, ese y los siguientes no muestran color (cascada)',
      'Objetivo próximo entreno es puntual: se resetea al cambiar de ejercicio, no persiste entre sesiones',
      'Flechas en "Último entreno" comparan ese entreno con el anterior a él (histórico), no con la sesión activa',
    ],
  },
  {
    version: '1.3.3',
    fecha: '28/04/2026',
    tipo: 'menor',
    cambios: [
      'Lógica de color en campos de peso corregida: serie 1 compara vs objetivo o máximo del último entreno, series 2+ vs la serie anterior',
      'Indicador ✗ rojo cuando el peso es inferior a la referencia',
      'Series iguales a la anterior no muestran color (neutro)',
    ],
  },
  {
    version: '1.3.2',
    fecha: '28/04/2026',
    tipo: 'media',
    cambios: [
      'Objetivo de peso se resetea automáticamente al completar la sesión si se alcanzó',
      'Animación 🎯💪 en el resumen si se superó algún objetivo de peso',
      'Campos de peso con color en tiempo real: verde si ≥ objetivo, rojo si < objetivo',
      'Indicador ✓ verde en el campo de peso cuando se supera el objetivo',
    ],
  },
  {
    version: '1.3.0',
    fecha: '28/04/2026',
    tipo: 'mayor',
    cambios: [
      'Botón Cancelar sesión en cabecera con modal de confirmación',
      'Eliminado selector de descanso entre series',
      'Nota fija del ejercicio visible (solo lectura) sobre la nota de sesión',
      'Aviso al guardar si alguna serie tiene reps o peso vacíos',
      'Objetivo próximo entreno: introducir peso objetivo con ↑/↓',
      'Tarjeta "Último entreno" muestra 🎯 objetivo con flecha verde/roja',
      'Datos de Rubén sincronizados a Supabase Y Google Sheets con Promise.allSettled',
    ],
  },
  {
    version: '1.2.2',
    fecha: '28/04/2026',
    tipo: 'media',
    cambios: [
      'PDF rediseñado: fondo negro, glow radial, líneas degradado, barras gradiente',
      'Gráficas de línea con área rellena y puntos destacados',
      'Pills oscuras para mejor marca y comparativa mes anterior',
      'Diseño premium futurista con paleta rojo/negro pura jsPDF',
    ],
  },
  {
    version: '1.2.1',
    fecha: '28/04/2026',
    tipo: 'media',
    cambios: [
      'Informe mensual PDF: descarga desde Tendencias con selector de mes',
      'PDF con nombre del usuario logado, sin referencias a "Rubén"',
      'PDF página 1: resumen (sesiones, series, kg totales, ejercicio del mes)',
      'PDF páginas siguientes: gráfica por ejercicio, mejor marca y comparativa mes anterior',
      'Limpieza automática de caché al hacer login (siempre última versión)',
    ],
  },
  {
    version: '1.2.0',
    fecha: '28/04/2026',
    tipo: 'mayor',
    cambios: [
      'Pantalla de resumen premium al finalizar sesión',
      'Vista visual con tarjeta por ejercicio: series, pesos en verde si superan histórico',
      'Comparativa automática con el último entreno (+Xkg / -Xkg)',
      'Indicador "Primera vez" en ejercicios sin historial',
      'Vista texto lista para copiar a WhatsApp con formato completo',
      'Botón "Copiar para WhatsApp" en un toque',
      'Confetti 💪 al aparecer el resumen',
      'Botón "Seguir editando" para volver y modificar antes de guardar',
    ],
  },
  {
    version: '1.1.0',
    fecha: '28/04/2026',
    tipo: 'mayor',
    cambios: [
      'Separación clara Rubén/Amigos: modo amigo activo al iniciar sesión',
      'Amigos solo ven rutinas y tendencias (sin peso, composición ni Google Sheets)',
      'Rutinas independientes por usuario almacenadas en Supabase',
      'Al registrarse, cada amigo recibe automáticamente la plantilla de ejercicios base',
      'Gestión de usuarios simplificada: solo nombre y contraseña',
      'Creación de usuario auto-inserta la plantilla de ejercicios en Supabase',
      'Sin zoom en móvil y sin scroll horizontal en toda la app',
    ],
  },
  {
    version: '1.0.0',
    fecha: '10/04/2026',
    tipo: 'mayor',
    cambios: [
      'Lanzamiento inicial de la app',
      'Sistema de login multiusuario con Supabase',
      'Registro de rutinas por día con series, pesos y repeticiones',
      'Indicadores de esfuerzo: Fallo, RIR 0, RIR 1',
      'Historial de último entreno en cada ejercicio',
      'Tendencias y gráficas de progreso muscular',
      'Registro de peso corporal con gráfica y media móvil',
      'Composición corporal: IMC, % grasa, % músculo',
      'Integración con Google Sheets',
      'PWA instalable en iPhone',
    ],
  },
]
